name: Scheduled Email Jobs

on:
  schedule:
    # Daily reminder email at 8:00 AM UTC
    - cron: '0 8 * * *'
    # Weekly digest email on Sundays at 9:00 AM UTC
    - cron: '0 9 * * 0'
  workflow_dispatch: # Allows manual triggering for testing

jobs:
  send-reminder-email:
    runs-on: ubuntu-latest
    # This job runs at 8:00 AM UTC daily
    if: github.event.schedule == '0 8 * * *' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Trigger reminder email API
        # Hard-coding the full URL for now
        run: |
          curl -X GET "https://goal-tracker-taupe.vercel.app//api/reminders/sendReminders" \
            -H "Authorization: Bearer ${{ secrets.RESEND_API_KEY }}" \
            -H "Content-Type: application/json" \
            -v
      - name: Log completion
        run: echo "Reminder email job completed at $(date)"

  send-weekly-digest:
    runs-on: ubuntu-latest
    # This job runs at 9:00 AM UTC on Sundays
    if: github.event.schedule == '0 9 * * 0' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Trigger weekly digest email API
        # Hard-coding the full URL for now
        run: |
          curl -X GET "https://goal-tracker-taupe.vercel.app//api/reminders/sendDigest" \
            -H "Authorization: Bearer ${{ secrets.RESEND_API_KEY }}" \
            -H "Content-Type: application/json" \
            -v
      - name: Log completion
        run: echo "Weekly digest job completed at $(date)" 